//tag::ref-doc[]
= JMS Source

The "jms" source enables receiving messages from JMS.

== Input

N/A

== Output

=== Headers

* `content-type: text/plain`

=== Payload

* `String`

=== Headers

* `content-type: application/octet-stream`

=== Payload

* `byte[]`

=== Headers

* `content-type: application/x-java-serialized-object`

=== Payload

* `java.io.Serializable`

=== Headers

* `content-type: application/x-java-object`

=== Payload

* `Map`

== Options

The **$$jms$$** $$source$$ has the following options:

//tag::configuration-properties[]
$$jms.client-id$$:: $$Client id for durable subscriptions.$$ *($$String$$, default: `$$<none>$$`)*
$$jms.destination$$:: $$The destination from which to receive messages (queue or topic).$$ *($$String$$, default: `$$<none>$$`)*
$$jms.message-selector$$:: $$A selector for messages;$$ *($$String$$, default: `$$<none>$$`)*
$$jms.session-transacted$$:: $$True to enable transactions and select a DefaultMessageListenerContainer, false to
 select a SimpleMessageListenerContainer.$$ *($$Boolean$$, default: `$$true$$`)*
$$jms.subscription-durable$$:: $$True for a durable subscription.$$ *($$Boolean$$, default: `$$<none>$$`)*
$$jms.subscription-name$$:: $$The name of a durable or shared subscription.$$ *($$String$$, default: `$$<none>$$`)*
$$jms.subscription-shared$$:: $$True for a shared subscription.$$ *($$Boolean$$, default: `$$<none>$$`)*
$$spring.jms.jndi-name$$:: $$Connection factory JNDI name. When set, takes precedence to others connection
 factory auto-configurations.$$ *($$String$$, default: `$$<none>$$`)*
$$spring.jms.listener.acknowledge-mode$$:: $$Acknowledge mode of the container. By default, the listener is transacted with
 automatic acknowledgment.$$ *($$AcknowledgeMode$$, default: `$$<none>$$`, possible values: `AUTO`,`CLIENT`,`DUPS_OK`)*
$$spring.jms.listener.auto-startup$$:: $$Start the container automatically on startup.$$ *($$Boolean$$, default: `$$true$$`)*
$$spring.jms.listener.concurrency$$:: $$Minimum number of concurrent consumers.$$ *($$Integer$$, default: `$$<none>$$`)*
$$spring.jms.listener.max-concurrency$$:: $$Maximum number of concurrent consumers.$$ *($$Integer$$, default: `$$<none>$$`)*
$$spring.jms.pub-sub-domain$$:: $$Specify if the default destination type is topic.$$ *($$Boolean$$, default: `$$false$$`)*
//end::configuration-properties[]


NOTE: Spring boot broker configuration is used; refer to the
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-jms[Spring Boot Documentation] for more information.
The `spring.jms.*` properties above are also handled by the boot JMS support.

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar jms-source.jar --jms.destination=
```

//end::ref-doc[]
